TO-DO.md
src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

Currently, our GET request simply gets all books in the database.
I want a filtration system. This change will introduce such a system in the backend only. Filters will be received in the form of HTTP request parameters.
This is my first pull request!

Filtration: Adding filtration by author and work title

---

TO-DO.md
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

Previously, we were only able to view books in the order in which they appear in the database.
Now, we can sort according to column names in ascending or descending order.
This requires a frontend change which will come later.

Sorting List: Adding sort_by and sorting_order HTTP request parameters

---

README.md
TO-DO.md
src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

First SonarCloud analysis, fixing what is feasible

Bugfix: Fixing some code smells

---

README.md
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/model/Book.java
src/main/java/com/example/aml/service/BookService.java

Changed work_name to work_title

---

README.md
src/main/java/com/example/aml/service/BookService.java

Bugfix: Ignoring case in keyword search

---

TO-DO.md
src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/model/AssociatedImage.java
src/main/java/com/example/aml/service/BookService.java
src/main/java/com/example/aml/utility/BookConstants.java

After adding an image table, I want to be able to upload and retrieve images to the database using API calls.
We added an image model and 2 request endpoints to the Controller. I might want to later separate the controllers.

Feature: Image PUT and GET requests

---

README.md
TO-DO.md
src/main/java/com/example/aml/dao/BookDataAccessService.java

Not an issue, just noticed a small change to be made

Bugfix: Adding picture UUIDs (if they exist) to our GET request responses

---

ManualScripts/csvPostRequests.py
ManualScripts/getAndPutImages.py
ManualScripts/updateImages.py
TO-DO.md

This script will automatically look for and add cover pictures for any book that:
a) currently doesn't have a picture, AND
b) can have a picture found using the book cover API (see changes)
Note: A nice feature to have. Eventually I intend to make this automatic every time we enter a book.

Feature: Add "update images" manual script

---

TO-DO.md
pom.xml
src/main/java/com/example/aml/service/BookCoverService.java
src/main/java/com/example/aml/service/BookService.java

When we insert a book, I'd like to call a service that looks for a book cover. This eliminates the need for those scripts that I wrote.
I do this by introducing a bookCoverService and calling the bookCover API (which isn't mine)
Closes #16

Feature: Automatic Book Cover Additions

---

.github/CODEOWNERS
.github/pull_request_template.md
.github/semantic.yml

**What?**
Adding a PR template, enforcing title format, and making myself a reviewer.
**Why?**
Cleanliness and consistency. Also because I want to see changes if others one day make them.
**How?**
Adding a pull_request_template to provide a basic PR template (in this form), semantic.yml (to enforce PR titles), and a CODEOWNERS file (to add myself as a code owner).

CI: Adding PR structure, title enforcements, and myself as a reviewer

---

TO-DO.md
src/main/java/com/example/aml/service/BookCoverService.java
src/main/resources/application.yml

Closes #40 
**What?**
Moving Book Cover Endpoint String to Application YAML
**Why?**
Cleanliness
**How?**
very basic change, see files changed

STYLING: Moving Book Cover Endpoint String to Application YAML

---

src/main/java/com/example/aml/service/BookService.java

Closes #46 
**What?**
Putting Book Cover API call into a non-blocking thread
**Why?**
Adding a book took too long, blocked by the api call to the book cover endpoint. Now, we do this in the background an adding a book is nearly instant.
**How?**
Running the call within an unassigned Thread object.

FEATURE: Putting Book Cover API call in background

---

src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dto/BookDTO.java
src/main/java/com/example/aml/mapper/BookDTOMapper.java
src/main/java/com/example/aml/model/Book.java
src/main/java/com/example/aml/service/BookService.java

Closes #28
**What?**
Introduce DTO for Book and a Book->BookDTO mapper
**Why?**
We want to hide some data in the Book model from the client.
**How?**
Creating a BookDTO that's used instead of Book that's used in the service and controller layers.

Feature: Introduce DTO for Book

---

src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/model/Book.java
src/main/java/com/example/aml/service/BookService.java

Closes #32 
**What?**
Adding _created_at_ and _updated_at_ **Date** fields to Model, not the DTO
**Why?**
In the future, we might want to sort by most recently added.
**How?**
Adding two fields to Model, relevant getters in data access layer, Date instantiations in Book constructors.

FEATURE: Adding created_at and updated_at Date fields

---

src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/dto/BookDTO.java
src/main/java/com/example/aml/mapper/BookDTOMapper.java
src/main/java/com/example/aml/model/Book.java
src/main/java/com/example/aml/service/BookService.java

Closes #21
**What?**
Add @JsonProperty to DTO Fields after DTO creation
**Why?**
The coupling of JSON and model fields is unnecessary and makes us use snake_case. Updated for BookDTO (dto) and Book (model) 
**How?**
https://www.baeldung.com/jackson-annotations#1-jsonproperty

FEATURE: Add @JsonProperty to DTO Fields 

---

src/main/java/com/example/aml/dao/BookDataAccessService.java

Closes #36 
**What?**
RowMapper as a single static field in DAO class.
**Why?**
Reduce code smells, write reusable code, DRY
**How?**
See files changed

STYLING: RowMapper Single Instantiation

---

src/main/java/com/example/aml/dao/BookDataAccessService.java

Closes #62 
**What?**
Stop using SELECT * and fix other code smells
**Why?**
SELECT * leads to errors if we change our table (ex. add a column)
**How?**
SELECT [insert list of wanted columns]

STYLING: Stop using SELECT * and fix other code smells

---

src/main/java/com/example/aml/dao/BookDataAccessService.java

Closes #65 
**What?**
Delete picture when deleting a book row
**Why?**
Our pictures DB is filling up with unnecessary information
**How?**
Performing GET request before deleting row, then deleting the picture using the picture_id from the GET request.

FEATURE: Delete picture when deleting a book row

---

src/main/java/com/example/aml/service/BookCoverService.java
src/main/java/com/example/aml/service/BookService.java

Closes #41 
**What?**
Replace book cover API call type with Optional<byte[]>
**Why?**
It's cleaner
**How?**
Use the Optional class

FEATURE: Replace book cover API call type with Optional<byte[]>

---

src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/dto/BookDTO.java
src/main/java/com/example/aml/mapper/BookDTOMapper.java
src/main/java/com/example/aml/model/Book.java
src/main/java/com/example/aml/service/BookService.java

Closes #35 
**What?**
Add genres String array to book table
**Why?**
We'd like to eventually filter books by genre.
**How?**
Adding string list to book db, DAO changes to accesses and RowMapper, adding String[] field to DTO and Model

FEATURE: Add genres String array to book table

---

.gitignore
README.md
pom.xml
src/main/resources/application.yml
src/main/resources/db/migration/V1__AML.sql
src/main/resources/db/migration/V1__BookTable.sql

Closes #69 
**What?**
I previously wasn't tracking my DB changes with flyway. Starting from now I will
**Why?**
It's helpful to have a history of our schema changes as we move forward.
**How?**
Integrate flyway into project, modify DDL script to be

FEATURE: Add Flyway to Project

---

src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDataAccessService.java

Closes #27 
**What?**
Change request return types to ResponseEntity
**Why?**
This will provide more information to the client and more flexibility in the future.
**How?**
Changing return types, add some null-checking logic.

FEATURE: Change request return types to ResponseEntity

---

src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

Closes #29 
**What?**
Add patch request endpoints for DTO fields
**Why?**
PATCH is used instead of PUT for individual fields
**How?**
Created two new endpoints; one for string fields and the other for integer fields. Further specifications are made in the parameter list.

FEATURE: Add patch request endpoints for DTO fields

---

Documentation/DOCUMENTATION.md
Documentation/EXTERNAL-APIs.md
Documentation/SETUP.md
README.md
pom.xml
src/main/resources/application.yml

Closes #20 
**What?**
Adding documentation
**Why?**
Help new devs become familiarized with codebase, and also help myself.
**How?**
Creating .md files

FEATURE: Starting to build documentation

---

src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

Closes #73 
**What?**
Adding endpoint that will support search bar.
**Why?**
I want to add a search bar to the frontend.
**How?**
Adding another endpoint + logic.

FEATURE: Add search by endpoint for title and author

---

src/main/java/com/example/aml/api/BookController.java
src/main/java/com/example/aml/dao/BookDao.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/dao/MockBookDataAccessService.java
src/main/java/com/example/aml/service/BookService.java

This reverts commit 4b1752c64a779ad4b935b89d762b7a993ed1b69d.

Revert "Add search by endpoint for title and author (#78)"

---

src/main/java/com/example/aml/service/BookService.java
src/main/java/com/example/aml/utility/BookConstants.java

Closes #37 
**What?**
Refuse duplicate entries
**Why?**
We don't want to have repeated entries
**How?**
Call the GET service function by name and author. If it returns something, then a book already exists.

Feature: Refuse duplicate entries

---

src/main/java/com/example/aml/service/BookService.java

Closes #30 
**What?**
Fix apostrophe issues
**Why?**
Many book and some author names have apostrophes. I'd like to able to search for them.
**How?**
Replacing the normal apostrophe with a special one before any DB operations

Feature: Fix apostrophe issues

---

src/main/java/com/example/aml/config/BookConfig.java
src/main/java/com/example/aml/dao/BookDataAccessService.java
src/main/java/com/example/aml/service/BookCoverService.java
src/main/java/com/example/aml/service/BookService.java
src/main/resources/application-local.yml
src/main/resources/application-test.yml
src/main/resources/application.yml
src/test/java/com/example/aml/integration/BookControllerTest.java
src/test/java/com/example/aml/service/BookServiceTest.java
src/test/java/com/example/aml/testUtils/BookTestConstants.java

Closes #90 
**What?**
**Why?**
**How?**

Feature: Add profiles and configuration properties file
